### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SimplGy** [Cocoanetics/XLIFFix#1]
Sorry bud, I don't understand the usage. It shows using it as a command line tool, but this is an xcode project, not an executable. What am I missing?

> Usage: XLIFFix path/to/lang.xliff

**Comment by SimplGy** [comment]
Never built a command line project from xcode before.
1. Run
2. Right click on the product, click open in finder
3. Open terminal
4. Drag the folder containing the executable to terminal (since the name is crazy long)
5. Execute against your xliff

That the easiest way? It does work for me.

**Comment by SimplGy** [comment]
Can I send you a PR that includes the executable in `App/Product` or wherever it's supposed to go?

**Comment by odrobnik** [comment]
After building the command line tool, you can install it in a convenient location, like `/usr/bin` or some other location that is in your path. Then you can run it everywhere.

PRs are welcome, generally speaking.
